apiVersion: v1
kind: Pod
metadata:
  name: pvc-debugger
spec:
  containers:
  - name: debugger
    image: ubuntu:latest
    env:
    - name: TZ
      value: "America/Los_Angeles"
    command: ["/bin/sh", "-c", "sleep infinity"] # Keep the pod running
    volumeMounts:
    - name: frame-storage
      mountPath: /frames
  volumes:
  - name: frame-storage
    persistentVolumeClaim:
      claimName: fogcat5-frames