apiVersion: apps/v1
kind: Deployment
metadata:
  name: frame-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frame-fetcher
  template:
    metadata:
      labels:
        app: frame-fetcher
    spec:
      containers:
      - name: frame-fetcher
        image: fogcat5/frame-fetcher:latest
        env:
        - name: YOUTUBE_URL
          value: "https://www.youtube.com/watch?v=hXtYKDio1rQ"
        volumeMounts:
        - mountPath: /frames
          name: frame-storage
      volumes:
      - name: frame-storage
        persistentVolumeClaim:
          claimName: fogcat5-frames
