apiVersion: v1
kind: Service
metadata:
  name: timelapse-web
  namespace: default
spec:
  selector:
    app: timelapse-web  # Matches labels on the pods
  ports:
  - protocol: TCP
    port: 5000          # Service port
    targetPort: 5000    # Container port
  type: ClusterIP
